ARG ARCH="amd64"
ARG ROS_VERSION="galactic"
FROM ${ARCH}/ros:${ROS_VERSION}-ros-base

# Install some dependencies used by the packages
RUN set -ex \
    && apt-get update && apt-get install -y \
        gdb \
        git

# Use rosdep to install the dependencies of the packages
COPY . /tmp/src/
RUN set -ex \
    && rosdep install --from-paths /tmp/src --ignore-src -r -y \
    && rm -rf /tmp/src

# Add a user that will be used when shelling into this container and allow them to use devices
ARG USER_ID=1000
ARG GROUP_ID=1000
RUN set -ex \
    && groupadd -g ${USER_ID} microstrain \
    && useradd -N -m -u ${USER_ID} -g ${GROUP_ID} -G "dialout" -s "/bin/bash" microstrain

# Make the directory where we will mount all the files into
USER microstrain
RUN echo "source /opt/ros/\${ROS_DISTRO}/setup.bash" >> ${HOME}/.bashrc
RUN mkdir -p ${HOME}/catkin_ws/src
RUN mkdir -p ${HOME}/catkin_ws/log
RUN mkdir -p ${HOME}/catkin_ws/build
RUN mkdir -p ${HOME}/catkin_ws/install
